/* SPDX-License-Identifier: Apache-2.0
 * Copyright 2026 Homero Leal
 */

/*
 * ipman — Implementation Plan Manager
 *
 * Per-invocation flow: require initialized home + DB, read stdin, parse
 * request, dispatch to handler, serialize response on stdout. Logs go to
 * stderr. `ipman init` creates the home + DB explicitly.
 *
 * Exit codes:
 *   0 — a well-formed response (ok:true or ok:false with a semantic error)
 *       was produced.
 *   1 — the protocol could not be executed: malformed input, internal
 *       error, DB unreachable, etc. A best-effort error envelope is still
 *       emitted on stdout so callers can surface the code. In b64 mode the
 *       stdout envelope is base64-encoded.
 */

#include "db.h"
#include "agent_docs.h"
#include "dispatch.h"
#include "import_ops.h"
#include "io.h"
#include "log.h"
#include "migrate_ops.h"
#include "sql_ops.h"
#include "migrations.h"
#include "ipman_home.h"
#include "ipman_key.h"
#include "protocol.h"
#include "render_md.h"
#include "skill_install.h"
#include "cli_output.h"
#include "cli_selector.h"
#include "version.h"

#include <cJSON.h>

#include <errno.h>
#include <libgen.h>
#include <limits.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/* Embedded usage text — generated by scripts/embed_usage.sh from
 * src/usage_text.txt. Declared here because main.c is the sole caller. */
extern const unsigned char ipman_usage_text[];
extern const size_t        ipman_usage_text_len;

static int g_b64_mode = 0;
static int g_dry_run  = 0;

/* Default cap on stdin payload size (16 MiB). Overridable per-process via the
 * IPMAN_MAX_REQUEST_BYTES env var. Mitigates OWASP A04 unbounded-input risk on
 * a CLI that any agent can pipe into. */
#define IPMAN_DEFAULT_MAX_REQUEST_BYTES (16u * 1024u * 1024u)

/* Parse IPMAN_MAX_REQUEST_BYTES. Returns the configured limit; on missing,
 * empty, or unparseable values, falls back to the default and logs once. */
static size_t resolve_max_request_bytes(void) {
    const char *raw = getenv("IPMAN_MAX_REQUEST_BYTES");
    if (raw == NULL || raw[0] == '\0') {
        return IPMAN_DEFAULT_MAX_REQUEST_BYTES;
    }
    errno = 0;
    char *endp = NULL;
    unsigned long long v = strtoull(raw, &endp, 10);
    if (errno != 0 || endp == raw || (endp != NULL && *endp != '\0')) {
        ipman_log_warn("invalid IPMAN_MAX_REQUEST_BYTES; using default",
                      "value=\"%s\" default=%u", raw,
                      (unsigned)IPMAN_DEFAULT_MAX_REQUEST_BYTES);
        return IPMAN_DEFAULT_MAX_REQUEST_BYTES;
    }
    if (v > (unsigned long long)((size_t)-1)) {
        ipman_log_warn("IPMAN_MAX_REQUEST_BYTES exceeds size_t; using default",
                      "value=\"%s\"", raw);
        return IPMAN_DEFAULT_MAX_REQUEST_BYTES;
    }
    return (size_t)v;
}

static void emit_response_text(const char *json) {
    static const char encode_fail_b64[] =
        "eyJyZXF1ZXN0X2lkIjpudWxsLCJvayI6ZmFsc2UsImVycm9yIjp7ImNvZGUiOiJpbnRlcm5hbF9lcnJvciIsIm1lc3NhZ2UiOiJmYWlsZWQgdG8gZW5jb2RlIHJlc3BvbnNlIn19";

    if (g_b64_mode) {
        char *encoded = NULL;
        if (ipman_base64_encode((const unsigned char *)json, strlen(json), &encoded) != 0) {
            fputs(encode_fail_b64, stdout);
            fputc('\n', stdout);
            return;
        }
        fputs(encoded, stdout);
        fputc('\n', stdout);
        free(encoded);
        return;
    }

    fputs(json, stdout);
    fputc('\n', stdout);
}

static void emit_response(cJSON *resp) {
    if (resp == NULL) {
        /* Out-of-memory during response construction. Produce the simplest
         * possible fatal envelope by hand so callers still get valid JSON. */
        const char *fallback =
            "{\"request_id\":null,\"ok\":false,"
            "\"error\":{\"code\":\"internal_error\","
            "\"message\":\"failed to build response\"}}";
        emit_response_text(fallback);
        return;
    }
    char *s = cJSON_PrintUnformatted(resp);
    if (s == NULL) {
        const char *fallback =
            "{\"request_id\":null,\"ok\":false,"
            "\"error\":{\"code\":\"internal_error\","
            "\"message\":\"failed to serialize response\"}}";
        emit_response_text(fallback);
        return;
    }

    emit_response_text(s);
    cJSON_free(s);
}

static int emit_fatal(const char *request_id, ipman_error_code_t code,
                      const char *msg) {
    cJSON *resp = ipman_response_err(request_id, code, msg, NULL);
    emit_response(resp);
    if (resp) cJSON_Delete(resp);
    return 1;
}

/* Like emit_fatal, but honors the semantic-vs-fatal distinction in
 * ipman_error_is_fatal: validation_failed/conflict/etc. produce a JSON
 * envelope on stdout with exit code 0, matching what the JSON dispatch
 * path does. CLI verbs use this for recoverable errors so callers can
 * cleanly distinguish "binary blew up" from "operation legitimately
 * declined". */
static int emit_op_error(const char *request_id, ipman_error_code_t code,
                         const char *msg) {
    cJSON *resp = ipman_response_err(request_id, code, msg, NULL);
    emit_response(resp);
    if (resp) cJSON_Delete(resp);
    return ipman_error_is_fatal(code) ? 1 : 0;
}

/* Human-readable nudge after a malformed JSON envelope. Stdout (the JSON
 * response) is unchanged; this only writes to stderr, which programmatic
 * consumers already ignore. Scoped to ipman_request_parse failures — never
 * fired on op-level errors, where the caller's envelope was well-formed. */
static void emit_parse_error_tip(void) {
    fputs("ipman: tip — try `ipman --usage` for CLI verbs, "
          "or `ipman --next` to see the active plan\n",
          stderr);
}

static void print_usage(FILE *out) {
    fprintf(out, "ipman %s - Implementation Plan Manager\n", IPMAN_VERSION);
    fwrite(ipman_usage_text, 1, ipman_usage_text_len, out);
}

static int build_db_path(const char *home, char *dbpath, size_t dbpath_len) {
    int n = snprintf(dbpath, dbpath_len, "%s/ipman.db", home);
    if (n < 0 || (size_t)n >= dbpath_len) {
        ipman_log_error("db path too long", "home=%s", home);
        return -1;
    }
    return 0;
}

static int open_workspace(sqlite3 **db_out, char *home, size_t home_len,
                          char *dbpath, size_t dbpath_len,
                          int create, int *schema_version_out) {
    if (ipman_home_resolve(home, home_len) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "cannot resolve ipman home");
    }
    if (create) {
        if (ipman_home_ensure(home) != 0) {
            return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                              "cannot prepare ipman home");
        }
        if (ipman_keysalt_ensure(home) != 0) {
            return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                              "cannot prepare keysalt");
        }
    } else if (ipman_home_require(home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                          "ipman workspace is not initialized; run `ipman init`");
    }

    if (build_db_path(home, dbpath, dbpath_len) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "db path too long");
    }
    if (!create && access(dbpath, F_OK) != 0) {
        ipman_log_error("ipman database missing", "path=%s", dbpath);
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                          "ipman workspace is not initialized; run `ipman init`");
    }

    sqlite3 *db = NULL;
    int db_rc = create ? ipman_db_open(home, dbpath, &db)
                       : ipman_db_open_existing(home, dbpath, &db);
    if (db_rc != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "cannot open database");
    }

    int schema_version = 0;
    if (ipman_migrations_apply(db, dbpath, &schema_version) != 0) {
        ipman_db_close(db);
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "migration apply failed");
    }

    if (ipman_agent_docs_refresh(home, dbpath, NULL) != 0) {
        ipman_db_close(db);
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                          "agent docs generation failed");
    }

    *db_out = db;
    if (schema_version_out != NULL) *schema_version_out = schema_version;
    return 0;
}

static int run_render(const char *selector) {
    char home[PATH_MAX];
    char dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    int rc = open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath,
                            0, NULL);
    if (rc != 0) return rc;

    sqlite3_int64 plan_id = 0;
    if (ipman_render_resolve_plan(db, selector, &plan_id) != 0) {
        fprintf(stderr, "ipman render: plan not found: %s\n", selector);
        ipman_db_close(db);
        return 1;
    }

    int render_rc = ipman_render_md(db, plan_id, stdout);
    ipman_db_close(db);
    return render_rc != 0 ? 1 : 0;
}

/*
 * On first init, the project row is seeded with name='unnamed' by migration
 * 0004. We can do better than that: the parent directory of IPMAN_HOME
 * almost always *is* the repo, so its basename is the natural project name.
 *
 * Behavior:
 *   - Resolves IPMAN_HOME to an absolute path with realpath().
 *   - Takes the basename of the parent directory (e.g. for ".ipman" inside
 *     a repo named "myapp", the parent is "myapp").
 *   - Updates the row only if name is still the literal default 'unnamed';
 *     never overwrites a user-supplied name.
 *
 * Failures here are non-fatal (we silently leave the default in place);
 * this is best-effort ergonomics, not a correctness requirement.
 */
static void auto_name_project_if_default(sqlite3 *db, const char *home) {
    /* Build an absolute path for `home` without relying on realpath() —
     * which is only declared under feature-test macros our build does
     * not enable. For relative paths, prepend cwd; for absolute paths
     * use as-is. We do not need symlink resolution here. */
    char abs[PATH_MAX];
    if (home[0] == '/') {
        int n = snprintf(abs, sizeof abs, "%s", home);
        if (n < 0 || (size_t)n >= sizeof abs) return;
    } else {
        char cwd[PATH_MAX];
        if (getcwd(cwd, sizeof cwd) == NULL) return;
        int n = snprintf(abs, sizeof abs, "%s/%s", cwd, home);
        if (n < 0 || (size_t)n >= sizeof abs) return;
    }

    /* dirname() and basename() may mutate their input; always use copies.
     *
     * Heuristic: if the home directory itself is `.ipman` (the default
     * convention from ipman_home.c — the workspace lives inside the repo),
     * the project name comes from the *parent* directory's basename. Any
     * other path means IPMAN_HOME was set explicitly, so we treat the
     * home directory itself as the project root and use its own basename. */
    char buf_for_base[PATH_MAX];
    int n = snprintf(buf_for_base, sizeof buf_for_base, "%s", abs);
    if (n < 0 || (size_t)n >= sizeof buf_for_base) return;
    char *home_basename = basename(buf_for_base);
    if (home_basename == NULL) return;

    char *base;
    char buf_for_parent[PATH_MAX];
    char buf_for_parent_base[PATH_MAX];
    if (strcmp(home_basename, ".ipman") == 0) {
        n = snprintf(buf_for_parent, sizeof buf_for_parent, "%s", abs);
        if (n < 0 || (size_t)n >= sizeof buf_for_parent) return;
        char *parent = dirname(buf_for_parent);
        if (parent == NULL) return;
        n = snprintf(buf_for_parent_base, sizeof buf_for_parent_base,
                     "%s", parent);
        if (n < 0 || (size_t)n >= sizeof buf_for_parent_base) return;
        base = basename(buf_for_parent_base);
    } else {
        base = home_basename;
    }
    if (base == NULL || *base == '\0' ||
        strcmp(base, "/") == 0 || strcmp(base, ".") == 0) {
        return;
    }

    const char *sql =
        "UPDATE project SET "
        "name = ?, "
        "updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') "
        "WHERE id = 1 AND name = 'unnamed';";
    sqlite3_stmt *stmt = NULL;
    if (sqlite3_prepare_v2(db, sql, -1, &stmt, NULL) != SQLITE_OK) return;
    sqlite3_bind_text(stmt, 1, base, -1, SQLITE_TRANSIENT);
    (void)sqlite3_step(stmt);
    sqlite3_finalize(stmt);
}

static int run_init(void) {
    /* Refuse `init` when cwd is inside a git repo but is NOT the repo
     * root. This is the silent-fork hazard the workspace discovery
     * upgrade in v2.4.2 closes: an agent in a subdir or worktree subdir
     * who runs `ipman init` would otherwise plant a stray .ipman/
     * alongside cwd, divorced from the data the user actually cares
     * about. The check is skipped when IPMAN_HOME is set explicitly
     * (operator escape hatch) and when we are not inside any repo at
     * all (legacy ad-hoc use). */
    char rel_root[PATH_MAX];
    if (ipman_home_repo_root_relpath(rel_root, sizeof rel_root) == 0 &&
        strcmp(rel_root, ".") != 0) {
        char msg[PATH_MAX + 200];
        snprintf(msg, sizeof msg,
                "init must run at the repo root (\"%s\" relative to cwd), "
                "not from a subdir or worktree subdir; cd to the root or "
                "set IPMAN_HOME explicitly to override",
                rel_root);
        return emit_op_error(NULL, IPMAN_ERR_VALIDATION_FAILED, msg);
    }

    char home[PATH_MAX];
    char dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    int schema_version = 0;
    int rc = open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath,
                            1, &schema_version);
    if (rc != 0) return rc;

    /* Populate the project row with the repo's directory basename when the
     * row is still its 'unnamed' default. Cheap ergonomics for first init. */
    auto_name_project_if_default(db, home);

    /* Best-effort: make the workspace-local skill discoverable for Claude
     * Code and Codex when the corresponding global install is absent. Failure
     * is logged but does not fail init — the workspace remains usable. */
    (void)ipman_skill_install();

    cJSON *result = cJSON_CreateObject();
    if (result != NULL) {
        cJSON_AddBoolToObject(result, "initialized", 1);
        cJSON_AddStringToObject(result, "home", home);
        cJSON_AddStringToObject(result, "db_path", dbpath);
        cJSON_AddNumberToObject(result, "schema_version", schema_version);
    }
    cJSON *resp = ipman_response_ok(NULL, result);
    emit_response(resp);
    if (resp) cJSON_Delete(resp);
    ipman_db_close(db);
    return 0;
}

static int run_migrate_encrypt(void) {
    char home[PATH_MAX];
    if (ipman_home_resolve(home, sizeof home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "cannot resolve ipman home");
    }
    if (ipman_home_require(home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                          "ipman workspace is not initialized; run `ipman init` first");
    }
    /* Ensure the keysalt exists before deriving — for workspaces that pre-date
     * the encryption work, this generates it on first migrate. */
    if (ipman_keysalt_ensure(home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "cannot prepare keysalt");
    }
    if (ipman_migrate_encrypt(home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "migrate-encrypt failed");
    }
    return 0;
}

/* Parse `ipman export --plaintext --i-understand <output>` argv (argv[1] is
 * already known to be the export verb). Order of the two flags is free, but
 * both are required; <output> is the lone positional. Mismatches print a
 * usage line on stderr and return non-zero. */
static int run_export(int argc, char **argv) {
    int saw_plaintext = 0;
    int saw_understand = 0;
    const char *out_path = NULL;
    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--plaintext") == 0) {
            saw_plaintext = 1;
        } else if (strcmp(argv[i], "--i-understand") == 0) {
            saw_understand = 1;
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "ipman export: unknown flag: %s\n", argv[i]);
            return 1;
        } else if (out_path == NULL) {
            out_path = argv[i];
        } else {
            fprintf(stderr, "ipman export: unexpected extra argument: %s\n",
                    argv[i]);
            return 1;
        }
    }
    if (!saw_plaintext) {
        fprintf(stderr,
                "ipman export: --plaintext is required (no other modes yet)\n");
        return 1;
    }
    if (!saw_understand) {
        fprintf(stderr,
                "ipman export --plaintext: refused without --i-understand.\n"
                "This writes an unencrypted copy of your DB; pass\n"
                "  --i-understand to acknowledge.\n");
        return 1;
    }
    if (out_path == NULL) {
        fprintf(stderr,
                "usage: ipman export --plaintext --i-understand <output.db>\n");
        return 1;
    }

    char home[PATH_MAX];
    if (ipman_home_resolve(home, sizeof home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "cannot resolve ipman home");
    }
    if (ipman_home_require(home) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL,
                          "ipman workspace is not initialized; run `ipman init` first");
    }
    if (ipman_export_plaintext(home, out_path) != 0) {
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "export --plaintext failed");
    }
    return 0;
}

/* Parse `ipman import-plan <file.json>` argv (argv[1] is already known to be
 * the import-plan verb). The sole positional argument is the JSON file path. */
static int run_import_plan(int argc, char **argv) {
    const char *json_path = NULL;
    for (int i = 2; i < argc; ++i) {
        if (argv[i][0] == '-') {
            fprintf(stderr, "ipman import-plan: unknown flag: %s\n", argv[i]);
            return 1;
        } else if (json_path == NULL) {
            json_path = argv[i];
        } else {
            fprintf(stderr, "ipman import-plan: unexpected extra argument: %s\n",
                    argv[i]);
            return 1;
        }
    }
    if (json_path == NULL) {
        fprintf(stderr, "usage: ipman import-plan <export.json>\n");
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    int ws_rc = open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath,
                               0, NULL);
    if (ws_rc != 0) return ws_rc;

    sqlite3_int64 new_plan_id = 0;
    char *err_msg = NULL;
    int rc = ipman_import_plan_envelope(db, json_path, &new_plan_id, &err_msg);
    ipman_db_close(db);

    if (rc != 0) {
        fprintf(stderr, "ipman import-plan: %s\n",
                err_msg ? err_msg : "import failed");
        free(err_msg);
        return 1;
    }
    free(err_msg);
    fprintf(stdout, "imported plan %lld\n", (long long)new_plan_id);
    return 0;
}

/* Developer / test escape-hatch: open the workspace through the standard
 * keyed open and run ad-hoc SQL. Output format mirrors `sqlite3` defaults
 * (one row per line, '|' between columns) so this drops in for tests that
 * previously called `sqlite3 "$DB" "..."`. Single SQL string as positional
 * argv. Errors land on stderr; rows on stdout. */
static int run_sql_cmd(int argc, char **argv) {
    const char *sql = NULL;
    for (int i = 2; i < argc; ++i) {
        if (argv[i][0] == '-' && argv[i][1] != '\0') {
            fprintf(stderr, "ipman sql: unknown flag: %s\n", argv[i]);
            return 1;
        } else if (sql == NULL) {
            sql = argv[i];
        } else {
            fprintf(stderr, "ipman sql: only one SQL string is supported "
                            "(got extra: %s)\n", argv[i]);
            return 1;
        }
    }
    if (sql == NULL) {
        fprintf(stderr, "usage: ipman sql \"SQL statement\"\n");
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    int ws_rc = open_workspace(&db, home, sizeof home,
                               dbpath, sizeof dbpath, 0, NULL);
    if (ws_rc != 0) return ws_rc;

    int sql_rc = ipman_sql_run(db, sql, stdout);
    ipman_db_close(db);
    return sql_rc != 0 ? 1 : 0;
}

/* ---- command parsing ---------------------------------------------- */

/* Map any supported form (bare word, -X, --word) to a canonical name.
 * Returns NULL for unrecognized tokens. */
static const char *parse_command(const char *arg) {
    if (arg == NULL) return NULL;
    if (strcmp(arg, "init")     == 0 || strcmp(arg, "-I")  == 0 || strcmp(arg, "--init")   == 0) return "init";
    if (strcmp(arg, "migrate-encrypt") == 0 || strcmp(arg, "--migrate-encrypt") == 0) return "migrate-encrypt";
    if (strcmp(arg, "export") == 0 || strcmp(arg, "--export") == 0) return "export";
    if (strcmp(arg, "sql") == 0 || strcmp(arg, "--sql") == 0) return "sql";
    if (strcmp(arg, "import-plan") == 0 || strcmp(arg, "--import-plan") == 0) return "import-plan";
    if (strcmp(arg, "render")   == 0 || strcmp(arg, "-R")  == 0 || strcmp(arg, "--render")  == 0) return "render";
    if (strcmp(arg, "status")   == 0 || strcmp(arg, "-S")  == 0 || strcmp(arg, "--status")  == 0) return "status";
    if (strcmp(arg, "ls")       == 0 || strcmp(arg, "-L")  == 0 || strcmp(arg, "--ls")      == 0) return "ls";
    if (strcmp(arg, "show")     == 0 || strcmp(arg, "-SH") == 0 || strcmp(arg, "--show")    == 0) return "show";
    if (strcmp(arg, "log")      == 0 || strcmp(arg, "-LG") == 0 || strcmp(arg, "--log")     == 0) return "log";
    if (strcmp(arg, "next")     == 0 || strcmp(arg, "-N")  == 0 || strcmp(arg, "--next")    == 0) return "next";
    if (strcmp(arg, "start")    == 0 ||                              strcmp(arg, "--start")   == 0) return "start";
    if (strcmp(arg, "close")    == 0 ||                              strcmp(arg, "--close")   == 0) return "close";
    if (strcmp(arg, "cancel")   == 0 ||                              strcmp(arg, "--cancel")  == 0) return "cancel";
    if (strcmp(arg, "close-phase")  == 0 ||                          strcmp(arg, "--close-phase")  == 0) return "close-phase";
    if (strcmp(arg, "cancel-phase") == 0 ||                          strcmp(arg, "--cancel-phase") == 0) return "cancel-phase";
    if (strcmp(arg, "defer")    == 0 ||                              strcmp(arg, "--defer")   == 0) return "defer";
    if (strcmp(arg, "current")  == 0 ||                              strcmp(arg, "--current") == 0) return "current";
    if (strcmp(arg, "activate") == 0 ||                              strcmp(arg, "--activate")== 0) return "activate";
    if (strcmp(arg, "b64")      == 0 || strcmp(arg, "-B")  == 0 || strcmp(arg, "--b64")     == 0) return "b64";
    if (strcmp(arg, "usage")    == 0 || strcmp(arg, "-U")  == 0 || strcmp(arg, "--usage")   == 0) return "usage";
    if (strcmp(arg, "version")  == 0 || strcmp(arg, "-V")  == 0 || strcmp(arg, "--version") == 0) return "version";
    return NULL;
}

/* ---- internal dispatch helper ------------------------------------- */

/* Call a read op from CLI context. Caller provides a cJSON params object
 * (may be an empty object; must not be NULL). Returns the detached
 * result node on success, NULL on error (message already printed to stderr).
 * Caller owns the returned cJSON and must free it with cJSON_Delete(). */
static cJSON *call_op(sqlite3 *db, const char *op, cJSON *params) {
    ipman_request_t req;
    memset(&req, 0, sizeof req);
    /* Synthetic in-process request: bypasses ipman_request_parse, so this
     * field is informational only. Set it to the real wire version (2) so
     * any future handler that inspects it sees the same value the agent
     * envelope carries on the actual JSON-on-stdin path. */
    req.protocol_version = 2;
    req.request_id       = "cli";
    req.actor            = "cli";
    req.op               = op;
    req.params           = params;
    req.root             = NULL;

    cJSON *response = NULL;
    ipman_dispatch(&req, db, &response);
    if (response == NULL) {
        fprintf(stderr, "ipman: internal error calling %s\n", op);
        return NULL;
    }

    cJSON *ok_item = cJSON_GetObjectItemCaseSensitive(response, "ok");
    if (!cJSON_IsTrue(ok_item)) {
        cJSON *err = cJSON_GetObjectItemCaseSensitive(response, "error");
        cJSON *msg = err ? cJSON_GetObjectItemCaseSensitive(err, "message") : NULL;
        fprintf(stderr, "ipman: %s\n",
                (msg && cJSON_IsString(msg)) ? msg->valuestring : "unknown error");
        cJSON_Delete(response);
        return NULL;
    }

    cJSON *result = cJSON_DetachItemFromObjectCaseSensitive(response, "result");
    cJSON_Delete(response);
    return result;
}

/* Print the v2 protocol envelope a write verb would dispatch, then exit
 * the verb without executing it. Used by --dry-run; the printed envelope
 * is valid JSON suitable for piping into `ipman` over stdin if the user
 * decides to run it. The synthetic request_id "dry-run-<verb>" makes
 * dry-run dispatches identifiable in any downstream logs. */
static void print_dry_run_envelope(const char *op, const cJSON *params,
                                   const char *verb) {
    cJSON *envelope = cJSON_CreateObject();
    cJSON_AddNumberToObject(envelope, "protocol_version", 2);
    char rid[64];
    snprintf(rid, sizeof rid, "dry-run-%s", verb);
    cJSON_AddStringToObject(envelope, "request_id", rid);
    cJSON_AddStringToObject(envelope, "actor",      "cli");
    cJSON_AddStringToObject(envelope, "op",         op);
    cJSON_AddItemToObject(envelope, "params", cJSON_Duplicate(params, 1));

    char *s = cJSON_Print(envelope);
    if (s != NULL) {
        fprintf(stdout, "%s\n", s);
        free(s);
    }
    cJSON_Delete(envelope);
}

/* ---- CLI shortcuts and views -------------------------------------- */

static int run_status(void) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    cJSON *ctx_params = cJSON_CreateObject();
    cJSON *ctx = call_op(db, "workspace.context_get", ctx_params);
    cJSON_Delete(ctx_params);
    if (ctx == NULL) { ipman_db_close(db); return 1; }

    cJSON *context     = cJSON_GetObjectItemCaseSensitive(ctx, "context");
    cJSON *active_plan = context ? cJSON_GetObjectItemCaseSensitive(context, "active_plan")  : NULL;
    cJSON *cur_phase   = context ? cJSON_GetObjectItemCaseSensitive(context, "current_phase") : NULL;
    cJSON *cur_task    = context ? cJSON_GetObjectItemCaseSensitive(context, "current_task")  : NULL;

    /* Build plan label: "CODE · Title" or "none" */
    char plan_val[256]  = "none";
    char phase_val[256] = "none";
    char task_val[256]  = "none";
    int  pending        = 0;

    if (cJSON_IsObject(active_plan)) {
        cJSON *code  = cJSON_GetObjectItemCaseSensitive(active_plan, "code");
        cJSON *title = cJSON_GetObjectItemCaseSensitive(active_plan, "title");
        snprintf(plan_val, sizeof plan_val, "%s · %s",
                 (code  && cJSON_IsString(code))  ? code->valuestring  : "?",
                 (title && cJSON_IsString(title))  ? title->valuestring : "?");

        /* Pending task count */
        cJSON *plan_id_item = cJSON_GetObjectItemCaseSensitive(active_plan, "id");
        if (cJSON_IsNumber(plan_id_item)) {
            cJSON *lp = cJSON_CreateObject();
            cJSON_AddNumberToObject(lp, "plan_id", plan_id_item->valuedouble);
            cJSON_AddBoolToObject(lp, "pending", 1);
            cJSON_AddNumberToObject(lp, "limit", 500);
            cJSON *lr = call_op(db, "task.list", lp);
            cJSON_Delete(lp);
            if (lr != NULL) {
                cJSON *tasks = cJSON_GetObjectItemCaseSensitive(lr, "tasks");
                if (cJSON_IsArray(tasks)) pending = cJSON_GetArraySize(tasks);
                cJSON_Delete(lr);
            }
        }
    }
    if (cJSON_IsObject(cur_phase)) {
        cJSON *label = cJSON_GetObjectItemCaseSensitive(cur_phase, "label");
        cJSON *title = cJSON_GetObjectItemCaseSensitive(cur_phase, "title");
        snprintf(phase_val, sizeof phase_val, "%s · %s",
                 (label && cJSON_IsString(label)) ? label->valuestring : "?",
                 (title && cJSON_IsString(title)) ? title->valuestring : "?");
    }
    if (cJSON_IsObject(cur_task)) {
        cJSON *label = cJSON_GetObjectItemCaseSensitive(cur_task, "label");
        cJSON *title = cJSON_GetObjectItemCaseSensitive(cur_task, "title");
        snprintf(task_val, sizeof task_val, "%s · %s",
                 (label && cJSON_IsString(label)) ? label->valuestring : "?",
                 (title && cJSON_IsString(title)) ? title->valuestring : "?");
    }

    char pending_str[32];
    snprintf(pending_str, sizeof pending_str, "%d", pending);

    cli_table_t t;
    const char *headers[] = {"Field", "Value"};
    cli_table_init(&t, 2, headers);
    const char *r0[] = {"Active plan",    plan_val};
    const char *r1[] = {"Current phase",  phase_val};
    const char *r2[] = {"Current task",   task_val};
    const char *r3[] = {"Pending tasks",  pending_str};
    cli_table_add_row(&t, r0);
    cli_table_add_row(&t, r1);
    cli_table_add_row(&t, r2);
    cli_table_add_row(&t, r3);
    cli_table_print(&t, stdout);
    cli_table_free(&t);

    cJSON_Delete(ctx);
    ipman_db_close(db);
    return 0;
}

static int run_ls(void) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    /* Get active plan id from context */
    cJSON *ctx_params = cJSON_CreateObject();
    cJSON *ctx = call_op(db, "workspace.context_get", ctx_params);
    cJSON_Delete(ctx_params);
    if (ctx == NULL) { ipman_db_close(db); return 1; }

    cJSON *context  = cJSON_GetObjectItemCaseSensitive(ctx, "context");
    cJSON *plan_obj = context ? cJSON_GetObjectItemCaseSensitive(context, "active_plan") : NULL;
    cJSON *plan_id  = plan_obj ? cJSON_GetObjectItemCaseSensitive(plan_obj, "id") : NULL;

    if (!cJSON_IsNumber(plan_id)) {
        fprintf(stderr, "ipman: no active plan — run `ipman --init` and `plan.activate`\n");
        cJSON_Delete(ctx);
        ipman_db_close(db);
        return 1;
    }

    cJSON *lp = cJSON_CreateObject();
    cJSON_AddNumberToObject(lp, "plan_id", plan_id->valuedouble);
    cJSON_AddBoolToObject(lp, "pending", 1);
    cJSON_AddNumberToObject(lp, "limit", 500);
    cJSON_Delete(ctx);

    cJSON *lr = call_op(db, "task.list", lp);
    cJSON_Delete(lp);
    if (lr == NULL) { ipman_db_close(db); return 1; }

    cli_table_t t;
    const char *headers[] = {"Label", "Priority", "Status", "Title"};
    cli_table_init(&t, 4, headers);

    cJSON *tasks = cJSON_GetObjectItemCaseSensitive(lr, "tasks");
    cJSON *task;
    cJSON_ArrayForEach(task, tasks) {
        cJSON *label    = cJSON_GetObjectItemCaseSensitive(task, "label");
        cJSON *priority = cJSON_GetObjectItemCaseSensitive(task, "priority");
        cJSON *status   = cJSON_GetObjectItemCaseSensitive(task, "status");
        cJSON *title    = cJSON_GetObjectItemCaseSensitive(task, "title");
        const char *row[] = {
            (label    && cJSON_IsString(label))    ? label->valuestring    : "",
            (priority && cJSON_IsString(priority)) ? priority->valuestring : "",
            (status   && cJSON_IsString(status))   ? status->valuestring   : "",
            (title    && cJSON_IsString(title))    ? title->valuestring    : "",
        };
        cli_table_add_row(&t, row);
    }

    cli_table_print(&t, stdout);
    cli_table_free(&t);
    cJSON_Delete(lr);
    ipman_db_close(db);
    return 0;
}

/* Fields to skip in --show output (internal or deprecated). */
static int show_skip_field(const char *name) {
    static const char * const skip[] = {
        "local_seq", "plan_id", "phase_id", "parent_task_id",
        "origin_task_id", NULL
    };
    for (int i = 0; skip[i]; i++)
        if (strcmp(name, skip[i]) == 0) return 1;
    return 0;
}

static int run_show(const char *selector) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK_OR_PHASE,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman show: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    const char *get_op = (kind == CLI_SELECTOR_KIND_TASK) ? "task.get"
                                                          : "phase.get";
    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id", (double)id);
    cJSON *result = call_op(db, get_op, p);
    cJSON_Delete(p);

    if (result == NULL) { ipman_db_close(db); return 1; }

    /* result has either "task" or "phase" key */
    cJSON *entity = cJSON_GetObjectItemCaseSensitive(result, "task");
    if (entity == NULL) entity = cJSON_GetObjectItemCaseSensitive(result, "phase");

    cli_table_t t;
    const char *headers[] = {"Field", "Value"};
    cli_table_init(&t, 2, headers);

    if (cJSON_IsObject(entity)) {
        cJSON *field;
        cJSON_ArrayForEach(field, entity) {
            if (field->string == NULL || show_skip_field(field->string)) continue;
            char val[512] = "";
            if (cJSON_IsString(field))      snprintf(val, sizeof val, "%s", field->valuestring);
            else if (cJSON_IsNumber(field)) snprintf(val, sizeof val, "%.0f", field->valuedouble);
            else if (cJSON_IsTrue(field))   snprintf(val, sizeof val, "true");
            else if (cJSON_IsFalse(field))  snprintf(val, sizeof val, "false");
            else if (cJSON_IsNull(field))   continue;
            else continue;
            const char *row[] = {field->string, val};
            cli_table_add_row(&t, row);
        }
    }

    cli_table_print(&t, stdout);
    cli_table_free(&t);
    cJSON_Delete(result);
    ipman_db_close(db);
    return 0;
}

/* --start <selector>: shortcut for task.transition({status:"in_progress"}).
 * Selector must resolve to a task (kind mismatch is rejected by the resolver). */
static int run_start(const char *selector) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman start: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id",     (double)id);
    cJSON_AddStringToObject(p, "status", "in_progress");
    if (g_dry_run) {
        print_dry_run_envelope("task.transition", p, "start");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "task.transition", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *task  = cJSON_GetObjectItemCaseSensitive(result, "task");
    cJSON *title = task ? cJSON_GetObjectItemCaseSensitive(task, "title") : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "started task %ld: %s\n", id, title->valuestring);
    else
        fprintf(stdout, "started task %ld\n", id);
    cJSON_Delete(result);
    return 0;
}

/*
 * Run a shell command via popen and return the first non-empty line of
 * stdout (newline-trimmed) as a heap string the caller must free, or NULL
 * if the command emitted nothing or exited non-zero. stderr is the caller's
 * responsibility — pass `2>/dev/null` in the command string to silence it.
 */
static char *git_capture_line(const char *cmd) {
    FILE *f = popen(cmd, "r");
    if (f == NULL) return NULL;
    char buf[256];
    char *line = NULL;
    if (fgets(buf, sizeof buf, f) != NULL) {
        size_t n = strlen(buf);
        while (n > 0 && (buf[n - 1] == '\n' || buf[n - 1] == '\r'))
            buf[--n] = 0;
        if (n > 0) line = strdup(buf);
    }
    /* Drain any remaining output so pclose doesn't block on a full pipe. */
    char drain[256];
    while (fgets(drain, sizeof drain, f) != NULL) { /* discard */ }
    int rc = pclose(f);
    if (rc != 0) {
        free(line);
        return NULL;
    }
    return line;
}

/*
 * Run a shell command and collect each stdout line as a string entry in a
 * new cJSON array (caller cJSON_Deletes). Returns NULL if popen fails or the
 * command exits non-zero (e.g. HEAD~1 missing on initial commit).
 */
static cJSON *git_capture_lines(const char *cmd) {
    FILE *f = popen(cmd, "r");
    if (f == NULL) return NULL;
    cJSON *arr = cJSON_CreateArray();
    if (arr == NULL) { pclose(f); return NULL; }
    char buf[1024];
    while (fgets(buf, sizeof buf, f) != NULL) {
        size_t n = strlen(buf);
        while (n > 0 && (buf[n - 1] == '\n' || buf[n - 1] == '\r'))
            buf[--n] = 0;
        if (n > 0) cJSON_AddItemToArray(arr, cJSON_CreateString(buf));
    }
    int rc = pclose(f);
    if (rc != 0) {
        cJSON_Delete(arr);
        return NULL;
    }
    return arr;
}

/* Returns 1 if the current working directory is inside a git work tree. */
static int git_in_repo(void) {
    FILE *f = popen("git rev-parse --is-inside-work-tree >/dev/null 2>&1",
                    "r");
    if (f == NULL) return 0;
    return pclose(f) == 0 ? 1 : 0;
}

/*
 * Inspect the working tree's dirty state. Returns 0 on success and writes
 * 1/0 into *dirty_out; -1 if the git command failed (caller should treat the
 * field as unknown / absent).
 */
static int git_status_dirty(int *dirty_out) {
    FILE *f = popen("git status --porcelain 2>/dev/null", "r");
    if (f == NULL) return -1;
    char buf[256];
    int has_changes = 0;
    while (fgets(buf, sizeof buf, f) != NULL) { has_changes = 1; }
    if (pclose(f) != 0) return -1;
    *dirty_out = has_changes;
    return 0;
}

/*
 * Split a comma-separated list of file paths into a cJSON string array.
 * Trims surrounding whitespace and drops empty entries.
 */
static cJSON *split_csv_to_array(const char *csv) {
    cJSON *arr = cJSON_CreateArray();
    if (arr == NULL) return NULL;
    char *dup = strdup(csv);
    if (dup == NULL) return arr;
    char *save = NULL;
    for (char *tok = strtok_r(dup, ",", &save); tok != NULL;
         tok = strtok_r(NULL, ",", &save)) {
        while (*tok == ' ' || *tok == '\t') tok++;
        char *end = tok + strlen(tok);
        while (end > tok && (end[-1] == ' ' || end[-1] == '\t')) --end;
        *end = 0;
        if (*tok) cJSON_AddItemToArray(arr, cJSON_CreateString(tok));
    }
    free(dup);
    return arr;
}

/*
 * Populate p with optional commit_sha / dirty / files_changed fields.
 *
 *  - --no-git suppresses every auto-capture and override (no git fields sent).
 *  - --commit / --files always win over auto-capture; they work even outside
 *    a repo so the user can attribute a closure manually.
 *  - When inside a repo and a field has no override, ipman shells out to git
 *    rev-parse / git status / git diff. Failure of any individual command is
 *    silent: the field stays absent so the consumer can distinguish "no git
 *    context" from "clean repo".
 */
static void apply_git_capture(cJSON *p, int no_git,
                              const char *commit_override,
                              const char *files_override) {
    if (no_git) return;
    int in_repo = git_in_repo();

    char *sha = NULL;
    if (commit_override != NULL) {
        sha = strdup(commit_override);
    } else if (in_repo) {
        sha = git_capture_line("git rev-parse HEAD 2>/dev/null");
    }
    if (sha != NULL) {
        cJSON_AddStringToObject(p, "commit_sha", sha);
        free(sha);
    }

    if (in_repo) {
        int dirty = 0;
        if (git_status_dirty(&dirty) == 0) {
            cJSON_AddBoolToObject(p, "dirty", dirty);
        }
    }

    cJSON *files = NULL;
    if (files_override != NULL) {
        files = split_csv_to_array(files_override);
    } else if (in_repo) {
        files = git_capture_lines("git diff --name-only HEAD~1 2>/dev/null");
    }
    if (files != NULL) cJSON_AddItemToObject(p, "files_changed", files);
}

/*
 * Parse a "--validation cmd:status" value into a {cmd, status} cJSON object
 * appended to *arr_inout (creating the array on first call). Returns 0 on
 * success or -1 with an error message on stderr. The split point is the
 * LAST colon: cmds may legitimately contain colons (URLs, paths), the
 * status is always a single trailing word.
 */
static int parse_validation_flag(const char *value, cJSON **arr_inout) {
    const char *colon = strrchr(value, ':');
    if (colon == NULL || colon == value || colon[1] == '\0') {
        fprintf(stderr,
                "ipman close: --validation value must be 'cmd:status'\n");
        return -1;
    }
    size_t cmd_len = (size_t)(colon - value);
    while (cmd_len > 0 &&
           (value[cmd_len - 1] == ' ' || value[cmd_len - 1] == '\t')) {
        cmd_len--;
    }
    if (cmd_len == 0) {
        fprintf(stderr, "ipman close: --validation cmd cannot be empty\n");
        return -1;
    }
    const char *status = colon + 1;
    while (*status == ' ' || *status == '\t') status++;
    if (*status == '\0') {
        fprintf(stderr,
                "ipman close: --validation status cannot be empty\n");
        return -1;
    }
    char *cmd = strndup(value, cmd_len);
    if (cmd == NULL) {
        fprintf(stderr, "ipman close: out of memory parsing --validation\n");
        return -1;
    }
    if (*arr_inout == NULL) {
        *arr_inout = cJSON_CreateArray();
        if (*arr_inout == NULL) { free(cmd); return -1; }
    }
    cJSON *entry = cJSON_CreateObject();
    if (entry == NULL) { free(cmd); return -1; }
    cJSON_AddStringToObject(entry, "cmd", cmd);
    cJSON_AddStringToObject(entry, "status", status);
    cJSON_AddItemToArray(*arr_inout, entry);
    free(cmd);
    return 0;
}

/* --close <selector> --summary <text> --comment <text>
 *                   [--lessons <text>] [--open-items <text>] [--followup]
 *                   [--commit <sha>] [--no-git] [--files <a,b,c>]
 *                   [--validation <cmd:status>]... [--decision <text>]...
 * Resolves a task selector, then dispatches task.close with the closure
 * fields. summary/comment are required (server-side too — validating CLI-side
 * gives a sharper diagnostic). When run inside a git repo, commit_sha, dirty,
 * and files_changed are auto-captured; --commit / --files override and
 * --no-git suppresses entirely. Outside a repo, the auto-capture silently
 * yields no fields. --validation and --decision are repeatable; status is any
 * non-empty string (the "passed"/"failed" convention is documentation, not
 * enforcement). */
static int run_close(int argc, char **argv) {
    const char *selector  = NULL;
    const char *summary   = NULL;
    const char *comment   = NULL;
    const char *lessons   = NULL;
    const char *open_items = NULL;
    const char *commit_override = NULL;
    const char *files_override  = NULL;
    int         followup  = 0;
    int         no_git    = 0;
    cJSON      *validations_arr = NULL;
    cJSON      *decisions_arr   = NULL;

    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--summary") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --summary requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            summary = argv[++i];
        } else if (strcmp(argv[i], "--comment") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --comment requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            comment = argv[++i];
        } else if (strcmp(argv[i], "--lessons") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --lessons requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            lessons = argv[++i];
        } else if (strcmp(argv[i], "--open-items") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --open-items requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            open_items = argv[++i];
        } else if (strcmp(argv[i], "--followup") == 0) {
            followup = 1;
        } else if (strcmp(argv[i], "--commit") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --commit requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            commit_override = argv[++i];
        } else if (strcmp(argv[i], "--no-git") == 0) {
            no_git = 1;
        } else if (strcmp(argv[i], "--files") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --files requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            files_override = argv[++i];
        } else if (strcmp(argv[i], "--validation") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --validation requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            if (parse_validation_flag(argv[++i], &validations_arr) != 0) {
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
        } else if (strcmp(argv[i], "--decision") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman close: --decision requires a value\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            const char *d = argv[++i];
            while (*d == ' ' || *d == '\t') d++;
            if (*d == '\0') {
                fprintf(stderr, "ipman close: --decision cannot be empty\n");
                if (validations_arr != NULL) cJSON_Delete(validations_arr);
                if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
                return 1;
            }
            if (decisions_arr == NULL) decisions_arr = cJSON_CreateArray();
            cJSON_AddItemToArray(decisions_arr, cJSON_CreateString(d));
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "ipman close: unknown flag: %s\n", argv[i]);
            if (validations_arr != NULL) cJSON_Delete(validations_arr);
            if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
            return 1;
        } else if (selector == NULL) {
            selector = argv[i];
        } else {
            fprintf(stderr, "ipman close: unexpected extra argument: %s\n",
                    argv[i]);
            if (validations_arr != NULL) cJSON_Delete(validations_arr);
            if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
            return 1;
        }
    }

    if (selector == NULL || summary == NULL || comment == NULL) {
        if (selector == NULL)
            fprintf(stderr, "ipman close: <selector> is required\n");
        if (summary == NULL)
            fprintf(stderr, "ipman close: --summary is required\n");
        if (comment == NULL)
            fprintf(stderr, "ipman close: --comment is required\n");
        fprintf(stderr,
                "usage: ipman --close <task-uid|label|id> "
                "--summary <text> --comment <text> "
                "[--lessons <text>] [--open-items <text>] [--followup] "
                "[--commit <sha>] [--no-git] [--files <a,b,c>] "
                "[--validation <cmd:status>]... [--decision <text>]...\n");
        if (validations_arr != NULL) cJSON_Delete(validations_arr);
        if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
        return 1;
    }

    if (no_git && (commit_override != NULL || files_override != NULL)) {
        fprintf(stderr,
                "ipman close: --no-git cannot be combined with "
                "--commit or --files\n");
        if (validations_arr != NULL) cJSON_Delete(validations_arr);
        if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0) {
        if (validations_arr != NULL) cJSON_Delete(validations_arr);
        if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
        return 1;
    }

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman close: %s\n", err);
        ipman_db_close(db);
        if (validations_arr != NULL) cJSON_Delete(validations_arr);
        if (decisions_arr   != NULL) cJSON_Delete(decisions_arr);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id",              (double)id);
    cJSON_AddStringToObject(p, "outcome_summary", summary);
    cJSON_AddStringToObject(p, "closing_comment", comment);
    if (lessons    != NULL) cJSON_AddStringToObject(p, "lessons_learned",    lessons);
    if (open_items != NULL) cJSON_AddStringToObject(p, "open_items_summary", open_items);
    if (followup)           cJSON_AddBoolToObject  (p, "followup_needed",    1);
    apply_git_capture(p, no_git, commit_override, files_override);
    if (validations_arr != NULL) cJSON_AddItemToObject(p, "validations_run", validations_arr);
    if (decisions_arr   != NULL) cJSON_AddItemToObject(p, "decisions",       decisions_arr);
    if (g_dry_run) {
        print_dry_run_envelope("task.close", p, "close");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "task.close", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *task  = cJSON_GetObjectItemCaseSensitive(result, "task");
    cJSON *title = task ? cJSON_GetObjectItemCaseSensitive(task, "title") : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "closed task %ld: %s\n", id, title->valuestring);
    else
        fprintf(stdout, "closed task %ld\n", id);
    cJSON_Delete(result);
    return 0;
}

/* --cancel <selector> --summary <text> --comment <text>
 * Resolves a task selector and dispatches task.cancel with
 * resolution=canceled. The shortcut does not expose the other resolutions
 * (not_planned, discarded, duplicate); use the raw protocol for those. */
static int run_cancel(int argc, char **argv) {
    const char *selector = NULL;
    const char *summary  = NULL;
    const char *comment  = NULL;

    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--summary") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman cancel: --summary requires a value\n");
                return 1;
            }
            summary = argv[++i];
        } else if (strcmp(argv[i], "--comment") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman cancel: --comment requires a value\n");
                return 1;
            }
            comment = argv[++i];
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "ipman cancel: unknown flag: %s\n", argv[i]);
            return 1;
        } else if (selector == NULL) {
            selector = argv[i];
        } else {
            fprintf(stderr, "ipman cancel: unexpected extra argument: %s\n",
                    argv[i]);
            return 1;
        }
    }

    if (selector == NULL || summary == NULL || comment == NULL) {
        if (selector == NULL)
            fprintf(stderr, "ipman cancel: <selector> is required\n");
        if (summary == NULL)
            fprintf(stderr, "ipman cancel: --summary is required\n");
        if (comment == NULL)
            fprintf(stderr, "ipman cancel: --comment is required\n");
        fprintf(stderr,
                "usage: ipman --cancel <task-uid|label|id> "
                "--summary <text> --comment <text>\n");
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman cancel: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id",              (double)id);
    cJSON_AddStringToObject(p, "resolution",      "canceled");
    cJSON_AddStringToObject(p, "outcome_summary", summary);
    cJSON_AddStringToObject(p, "closing_comment", comment);
    if (g_dry_run) {
        print_dry_run_envelope("task.cancel", p, "cancel");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "task.cancel", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *task  = cJSON_GetObjectItemCaseSensitive(result, "task");
    cJSON *title = task ? cJSON_GetObjectItemCaseSensitive(task, "title") : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "canceled task %ld: %s\n", id, title->valuestring);
    else
        fprintf(stdout, "canceled task %ld\n", id);
    cJSON_Delete(result);
    return 0;
}

/* --close-phase  <selector> --summary <text> --comment <text>
 *                          [--lessons <text>] [--open-items <text>] [--followup]
 * --cancel-phase <selector> --summary <text> --comment <text>
 *                          [--lessons <text>] [--open-items <text>] [--followup]
 *
 * Both verbs serialize to phase.close — the wire op is single-target and
 * selects between resolutions via its `outcome` field
 * (completed | canceled). The CLI exposes two named verbs (rather than a
 * polymorphic --close) so the audit trail in the shell history matches the
 * resolution recorded in closure memory. phase.close does not accept the
 * validations_run / decisions / git auto-capture fields that task.close does,
 * so those flags are intentionally absent here.
 *
 * `cancel` is non-NULL ("canceled") for the cancel verb and NULL for close,
 * which selects the verb name in error messages, dry-run request_id, and
 * the success line printed to stdout. */
static int run_close_or_cancel_phase(int argc, char **argv,
                                     const char *cancel_outcome) {
    const char *verb = (cancel_outcome != NULL) ? "cancel-phase" : "close-phase";
    const char *selector  = NULL;
    const char *summary   = NULL;
    const char *comment   = NULL;
    const char *lessons   = NULL;
    const char *open_items = NULL;
    int         followup  = 0;

    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--summary") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman %s: --summary requires a value\n", verb);
                return 1;
            }
            summary = argv[++i];
        } else if (strcmp(argv[i], "--comment") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman %s: --comment requires a value\n", verb);
                return 1;
            }
            comment = argv[++i];
        } else if (strcmp(argv[i], "--lessons") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman %s: --lessons requires a value\n", verb);
                return 1;
            }
            lessons = argv[++i];
        } else if (strcmp(argv[i], "--open-items") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman %s: --open-items requires a value\n", verb);
                return 1;
            }
            open_items = argv[++i];
        } else if (strcmp(argv[i], "--followup") == 0) {
            followup = 1;
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "ipman %s: unknown flag: %s\n", verb, argv[i]);
            return 1;
        } else if (selector == NULL) {
            selector = argv[i];
        } else {
            fprintf(stderr, "ipman %s: unexpected extra argument: %s\n",
                    verb, argv[i]);
            return 1;
        }
    }

    if (selector == NULL || summary == NULL || comment == NULL) {
        if (selector == NULL)
            fprintf(stderr, "ipman %s: <selector> is required\n", verb);
        if (summary == NULL)
            fprintf(stderr, "ipman %s: --summary is required\n", verb);
        if (comment == NULL)
            fprintf(stderr, "ipman %s: --comment is required\n", verb);
        fprintf(stderr,
                "usage: ipman --%s <phase-uid|label|id> "
                "--summary <text> --comment <text> "
                "[--lessons <text>] [--open-items <text>] [--followup]\n",
                verb);
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_PHASE,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman %s: %s\n", verb, err);
        ipman_db_close(db);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id", (double)id);
    cJSON_AddStringToObject(p, "outcome",
                            (cancel_outcome != NULL) ? cancel_outcome : "completed");
    cJSON_AddStringToObject(p, "outcome_summary", summary);
    cJSON_AddStringToObject(p, "closing_comment", comment);
    if (lessons    != NULL) cJSON_AddStringToObject(p, "lessons_learned",    lessons);
    if (open_items != NULL) cJSON_AddStringToObject(p, "open_items_summary", open_items);
    if (followup)           cJSON_AddBoolToObject  (p, "followup_needed",    1);
    if (g_dry_run) {
        print_dry_run_envelope("phase.close", p, verb);
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "phase.close", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    const char *past = (cancel_outcome != NULL) ? "canceled" : "closed";
    cJSON *phase = cJSON_GetObjectItemCaseSensitive(result, "phase");
    cJSON *title = phase ? cJSON_GetObjectItemCaseSensitive(phase, "title") : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "%s phase %ld: %s\n", past, id, title->valuestring);
    else
        fprintf(stdout, "%s phase %ld\n", past, id);
    cJSON_Delete(result);
    return 0;
}

static int run_close_phase(int argc, char **argv) {
    return run_close_or_cancel_phase(argc, argv, NULL);
}

static int run_cancel_phase(int argc, char **argv) {
    return run_close_or_cancel_phase(argc, argv, "canceled");
}

/* --defer <selector> --reason-text <text> [--reason-code <code>]
 * Resolves a task selector and dispatches task.defer. The shortcut
 * requires --reason-text (the protocol allows reason_code alone, but free
 * text guarantees the audit trail stays human-readable). --reason-code is
 * optional and only sent when provided; deferred_until is not exposed —
 * use the raw protocol for scheduled deferrals. */
static int run_defer(int argc, char **argv) {
    const char *selector    = NULL;
    const char *reason_text = NULL;
    const char *reason_code = NULL;

    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--reason-text") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman defer: --reason-text requires a value\n");
                return 1;
            }
            reason_text = argv[++i];
        } else if (strcmp(argv[i], "--reason-code") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman defer: --reason-code requires a value\n");
                return 1;
            }
            reason_code = argv[++i];
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "ipman defer: unknown flag: %s\n", argv[i]);
            return 1;
        } else if (selector == NULL) {
            selector = argv[i];
        } else {
            fprintf(stderr, "ipman defer: unexpected extra argument: %s\n",
                    argv[i]);
            return 1;
        }
    }

    if (selector == NULL || reason_text == NULL) {
        if (selector == NULL)
            fprintf(stderr, "ipman defer: <selector> is required\n");
        if (reason_text == NULL)
            fprintf(stderr, "ipman defer: --reason-text is required\n");
        fprintf(stderr,
                "usage: ipman --defer <task-uid|label|id> "
                "--reason-text <text> [--reason-code <code>]\n");
        return 1;
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman defer: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id",          (double)id);
    cJSON_AddStringToObject(p, "reason_text", reason_text);
    if (reason_code != NULL)
        cJSON_AddStringToObject(p, "reason_code", reason_code);
    if (g_dry_run) {
        print_dry_run_envelope("task.defer", p, "defer");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "task.defer", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *task  = cJSON_GetObjectItemCaseSensitive(result, "task");
    cJSON *title = task ? cJSON_GetObjectItemCaseSensitive(task, "title") : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "deferred task %ld: %s\n", id, title->valuestring);
    else
        fprintf(stdout, "deferred task %ld\n", id);
    cJSON_Delete(result);
    return 0;
}

/* --current <selector>: shortcut to set the current task or phase.
 * Dispatches task.set_current or phase.set_current depending on resolved kind.
 * The resolver auto-detects kind (task or phase) and routes to the matching
 * op. Plans are rejected at the resolver — use --activate for plans. */
static int run_current(const char *selector) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_TASK_OR_PHASE,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman current: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    const char *op_name      = (kind == CLI_SELECTOR_KIND_TASK)
                               ? "task.set_current" : "phase.set_current";
    const char *entity_label = (kind == CLI_SELECTOR_KIND_TASK)
                               ? "task" : "phase";
    const char *context_key  = (kind == CLI_SELECTOR_KIND_TASK)
                               ? "current_task" : "current_phase";

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id", (double)id);
    if (g_dry_run) {
        print_dry_run_envelope(op_name, p, "current");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, op_name, p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *context = cJSON_GetObjectItemCaseSensitive(result, "context");
    cJSON *entity  = context ? cJSON_GetObjectItemCaseSensitive(context, context_key) : NULL;
    cJSON *title   = entity  ? cJSON_GetObjectItemCaseSensitive(entity, "title")      : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "set current %s %ld: %s\n", entity_label, id, title->valuestring);
    else
        fprintf(stdout, "set current %s %ld\n", entity_label, id);
    cJSON_Delete(result);
    return 0;
}

/* --activate <selector>: shortcut for plan.activate.
 * Selector must resolve to a plan (kind mismatch is rejected by the resolver). */
static int run_activate(const char *selector) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    long id = 0;
    cli_selector_kind_t kind = 0;
    char err[CLI_SELECTOR_ERR_LEN];
    if (cli_resolve_selector(db, selector, CLI_SELECTOR_KIND_PLAN,
                             &id, &kind, err, sizeof err) != 0) {
        fprintf(stderr, "ipman activate: %s\n", err);
        ipman_db_close(db);
        return 1;
    }

    cJSON *p = cJSON_CreateObject();
    cJSON_AddNumberToObject(p, "id", (double)id);
    if (g_dry_run) {
        print_dry_run_envelope("plan.activate", p, "activate");
        cJSON_Delete(p);
        ipman_db_close(db);
        return 0;
    }
    cJSON *result = call_op(db, "plan.activate", p);
    cJSON_Delete(p);
    ipman_db_close(db);

    if (result == NULL) return 1;

    cJSON *context = cJSON_GetObjectItemCaseSensitive(result, "context");
    cJSON *plan    = context ? cJSON_GetObjectItemCaseSensitive(context, "active_plan") : NULL;
    cJSON *title   = plan    ? cJSON_GetObjectItemCaseSensitive(plan, "title")          : NULL;
    if (title && cJSON_IsString(title))
        fprintf(stdout, "activated plan %ld: %s\n", id, title->valuestring);
    else
        fprintf(stdout, "activated plan %ld\n", id);
    cJSON_Delete(result);
    return 0;
}

/* Add a Field/Value row to t when v is a non-empty string. JSON null,
 * non-strings and empty strings are skipped — matches the run_show
 * convention of hiding fields that are not meaningfully populated. */
static void add_str_row(cli_table_t *t, const char *field, const cJSON *v) {
    if (v == NULL || !cJSON_IsString(v)) return;
    const char *s = v->valuestring;
    if (s == NULL || s[0] == '\0') return;
    const char *row[] = { field, s };
    cli_table_add_row(t, row);
}

/* Banner + Field/Value detail table for one cursor level. The banner prefers
 * `code` (plans only) and falls back to `label` (phases/tasks) so v2.0
 * responses, which dropped `code`, still get a meaningful identifier in the
 * heading. include_priority adds the priority row (plans/tasks have it,
 * phases don't). When entity is NULL the banner reports "(none)" and no
 * table is drawn. */
static void next_print_cursor(FILE *out, const char *kind,
                              int include_priority,
                              const cJSON *entity) {
    if (!cJSON_IsObject(entity)) {
        fprintf(out, "%s: (none)\n", kind);
        return;
    }
    cJSON *code  = cJSON_GetObjectItemCaseSensitive(entity, "code");
    cJSON *label = cJSON_GetObjectItemCaseSensitive(entity, "label");
    cJSON *title = cJSON_GetObjectItemCaseSensitive(entity, "title");
    const char *id_str = "?";
    if (code  && cJSON_IsString(code)  && code->valuestring[0]  != '\0') id_str = code->valuestring;
    else if (label && cJSON_IsString(label) && label->valuestring[0] != '\0') id_str = label->valuestring;
    fprintf(out, "%s: %s · %s\n", kind, id_str,
            (title && cJSON_IsString(title)) ? title->valuestring : "?");

    cli_table_t t;
    const char *headers[] = {"Field", "Value"};
    cli_table_init(&t, 2, headers);
    add_str_row(&t, "Status",      cJSON_GetObjectItemCaseSensitive(entity, "status"));
    if (include_priority)
        add_str_row(&t, "Priority", cJSON_GetObjectItemCaseSensitive(entity, "priority"));
    add_str_row(&t, "Summary",     cJSON_GetObjectItemCaseSensitive(entity, "summary"));
    add_str_row(&t, "Description", cJSON_GetObjectItemCaseSensitive(entity, "description"));
    cli_table_print(&t, out);
    cli_table_free(&t);
}

/* Project block renderer for --next. Skips empty subsections so the
 * banner stays compact for fresh workspaces. */
static void next_print_project(FILE *out, const cJSON *project) {
    if (!cJSON_IsObject(project)) return;
    const cJSON *name = cJSON_GetObjectItemCaseSensitive(project, "name");
    const cJSON *desc = cJSON_GetObjectItemCaseSensitive(project, "description");
    fprintf(out, "Project: %s\n",
            (name && cJSON_IsString(name)) ? name->valuestring : "?");
    if (desc && cJSON_IsString(desc) && desc->valuestring[0] != '\0') {
        fprintf(out, "Description: %s\n", desc->valuestring);
    }

    const cJSON *tools = cJSON_GetObjectItemCaseSensitive(project, "tools");
    if (cJSON_IsArray(tools) && cJSON_GetArraySize(tools) > 0) {
        fputs("\nTools\n", out);
        cli_table_t tt;
        const char *thdr[] = {"Name", "Version", "Required", "Purpose"};
        cli_table_init(&tt, 4, thdr);
        const cJSON *t;
        cJSON_ArrayForEach(t, tools) {
            const cJSON *tn = cJSON_GetObjectItemCaseSensitive(t, "name");
            const cJSON *tv = cJSON_GetObjectItemCaseSensitive(t, "version_constraint");
            const cJSON *tr = cJSON_GetObjectItemCaseSensitive(t, "required");
            const cJSON *tp = cJSON_GetObjectItemCaseSensitive(t, "purpose");
            const char *row[] = {
                (tn && cJSON_IsString(tn)) ? tn->valuestring : "",
                (tv && cJSON_IsString(tv)) ? tv->valuestring : "",
                cJSON_IsTrue(tr) ? "yes" : "no",
                (tp && cJSON_IsString(tp)) ? tp->valuestring : "",
            };
            cli_table_add_row(&tt, row);
        }
        cli_table_print(&tt, out);
        cli_table_free(&tt);
    }

    const cJSON *envs = cJSON_GetObjectItemCaseSensitive(project, "env_vars");
    if (cJSON_IsArray(envs) && cJSON_GetArraySize(envs) > 0) {
        fputs("\nEnv vars\n", out);
        cli_table_t et;
        const char *ehdr[] = {"Name", "Required", "Sensitive", "Purpose"};
        cli_table_init(&et, 4, ehdr);
        const cJSON *e;
        cJSON_ArrayForEach(e, envs) {
            const cJSON *en = cJSON_GetObjectItemCaseSensitive(e, "name");
            const cJSON *er = cJSON_GetObjectItemCaseSensitive(e, "required");
            const cJSON *es = cJSON_GetObjectItemCaseSensitive(e, "sensitive");
            const cJSON *ep = cJSON_GetObjectItemCaseSensitive(e, "purpose");
            const char *row[] = {
                (en && cJSON_IsString(en)) ? en->valuestring : "",
                cJSON_IsTrue(er) ? "yes" : "no",
                cJSON_IsTrue(es) ? "yes" : "no",
                (ep && cJSON_IsString(ep)) ? ep->valuestring : "",
            };
            cli_table_add_row(&et, row);
        }
        cli_table_print(&et, out);
        cli_table_free(&et);
    }

    const cJSON *pi = cJSON_GetObjectItemCaseSensitive(project, "instructions");
    if (cJSON_IsArray(pi) && cJSON_GetArraySize(pi) > 0) {
        fputs("\nProject instructions\n", out);
        cli_table_t pt;
        const char *phdr[] = {"Type", "Body"};
        cli_table_init(&pt, 2, phdr);
        const cJSON *e;
        cJSON_ArrayForEach(e, pi) {
            const cJSON *body  = cJSON_GetObjectItemCaseSensitive(e, "body");
            const cJSON *itype = cJSON_GetObjectItemCaseSensitive(e, "instruction_type");
            const char *row[] = {
                (itype && cJSON_IsString(itype)) ? itype->valuestring : "",
                (body  && cJSON_IsString(body))  ? body->valuestring  : "",
            };
            cli_table_add_row(&pt, row);
        }
        cli_table_print(&pt, out);
        cli_table_free(&pt);
    }
}

/* Section renderer for --next: project banner + per-cursor Field/Value
 * tables, a unified instructions table with a Scope column, and an Up
 * next table matching --ls. Helper kept separate from run_next so the
 * data-fetch pipeline above is not entangled with rendering choices. */
static void next_render(const cJSON *project,
                        const cJSON *plan_obj,
                        const cJSON *phase_obj,
                        const cJSON *task_obj,
                        const cJSON *plan_instr,
                        const cJSON *phase_instr,
                        const cJSON *task_instr,
                        const cJSON *pending) {
    next_print_project(stdout, project);
    fputc('\n', stdout);
    next_print_cursor(stdout, "Plan",  /*priority=*/1, plan_obj);
    next_print_cursor(stdout, "Phase", /*priority=*/0, phase_obj);
    next_print_cursor(stdout, "Task",  /*priority=*/1, task_obj);

    fputs("\nInstructions\n", stdout);
    cli_table_t it;
    const char *ihdr[] = {"Scope", "Type", "Body"};
    cli_table_init(&it, 3, ihdr);
    const cJSON *scopes[3] = { plan_instr, phase_instr, task_instr };
    const char  *labels[3] = { "plan", "phase", "task" };
    for (int i = 0; i < 3; i++) {
        if (scopes[i] == NULL) continue;
        const cJSON *list = cJSON_GetObjectItemCaseSensitive(scopes[i], "instructions");
        const cJSON *entry;
        cJSON_ArrayForEach(entry, list) {
            cJSON *body  = cJSON_GetObjectItemCaseSensitive(entry, "body");
            cJSON *itype = cJSON_GetObjectItemCaseSensitive(entry, "instruction_type");
            const char *row[] = {
                labels[i],
                (itype && cJSON_IsString(itype)) ? itype->valuestring : "",
                (body  && cJSON_IsString(body))  ? body->valuestring  : "",
            };
            cli_table_add_row(&it, row);
        }
    }
    cli_table_print(&it, stdout);
    cli_table_free(&it);

    fputs("\nUp next (pending)\n", stdout);
    cli_table_t up;
    const char *uhdr[] = {"Label", "Priority", "Status", "Title"};
    cli_table_init(&up, 4, uhdr);
    if (pending != NULL) {
        const cJSON *list = cJSON_GetObjectItemCaseSensitive(pending, "tasks");
        const cJSON *t;
        cJSON_ArrayForEach(t, list) {
            cJSON *label    = cJSON_GetObjectItemCaseSensitive(t, "label");
            cJSON *priority = cJSON_GetObjectItemCaseSensitive(t, "priority");
            cJSON *status   = cJSON_GetObjectItemCaseSensitive(t, "status");
            cJSON *title    = cJSON_GetObjectItemCaseSensitive(t, "title");
            const char *row[] = {
                (label    && cJSON_IsString(label))    ? label->valuestring    : "",
                (priority && cJSON_IsString(priority)) ? priority->valuestring : "",
                (status   && cJSON_IsString(status))   ? status->valuestring   : "",
                (title    && cJSON_IsString(title))    ? title->valuestring    : "",
            };
            cli_table_add_row(&up, row);
        }
    }
    cli_table_print(&up, stdout);
    cli_table_free(&up);
}

/* --next: combined read-only view that replaces the typical agent
 * handoff sequence (workspace.context_get + plan/phase/task.get +
 * instruction.list per scope + task.list pending) with a single CLI
 * call. */
static int run_next(void) {
    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    /* 1. workspace.context_get → cursor IDs */
    cJSON *ctx_params = cJSON_CreateObject();
    cJSON *ctx = call_op(db, "workspace.context_get", ctx_params);
    cJSON_Delete(ctx_params);
    if (ctx == NULL) { ipman_db_close(db); return 1; }

    cJSON *context  = cJSON_GetObjectItemCaseSensitive(ctx, "context");
    cJSON *ap_id    = context ? cJSON_GetObjectItemCaseSensitive(context, "active_plan_id")   : NULL;
    cJSON *cph_id   = context ? cJSON_GetObjectItemCaseSensitive(context, "current_phase_id") : NULL;
    cJSON *ctk_id   = context ? cJSON_GetObjectItemCaseSensitive(context, "current_task_id")  : NULL;
    long plan_id  = (cJSON_IsNumber(ap_id))  ? (long)ap_id->valuedouble  : 0;
    long phase_id = (cJSON_IsNumber(cph_id)) ? (long)cph_id->valuedouble : 0;
    long task_id  = (cJSON_IsNumber(ctk_id)) ? (long)ctk_id->valuedouble : 0;
    cJSON *project = context ? cJSON_DetachItemFromObjectCaseSensitive(context, "project") : NULL;
    cJSON_Delete(ctx);

    if (plan_id <= 0) {
        /* No active plan, but the project block is still useful: tools,
         * env_vars, and project-scoped instructions reach the agent
         * regardless of cursor state. Render it and surface a hint. */
        next_print_project(stdout, project);
        if (project) cJSON_Delete(project);
        fprintf(stderr,
                "ipman next: no active plan — run `ipman --activate <plan>` first\n");
        ipman_db_close(db);
        return 1;
    }

    /* 2-4. plan.get / phase.get / task.get for full, authoritative entities. */
    cJSON *plan_obj = NULL, *phase_obj = NULL, *task_obj = NULL;
    {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddNumberToObject(p, "id", (double)plan_id);
        cJSON *r = call_op(db, "plan.get", p);
        cJSON_Delete(p);
        if (r == NULL) { ipman_db_close(db); return 1; }
        plan_obj = cJSON_DetachItemFromObjectCaseSensitive(r, "plan");
        cJSON_Delete(r);
    }
    if (phase_id > 0) {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddNumberToObject(p, "id", (double)phase_id);
        cJSON *r = call_op(db, "phase.get", p);
        cJSON_Delete(p);
        if (r != NULL) {
            phase_obj = cJSON_DetachItemFromObjectCaseSensitive(r, "phase");
            cJSON_Delete(r);
        }
    }
    if (task_id > 0) {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddNumberToObject(p, "id", (double)task_id);
        cJSON *r = call_op(db, "task.get", p);
        cJSON_Delete(p);
        if (r != NULL) {
            task_obj = cJSON_DetachItemFromObjectCaseSensitive(r, "task");
            cJSON_Delete(r);
        }
    }

    /* 5-7. instruction.list per scope. Phase / task scopes only when
     * the cursor is set; otherwise the entity_id would be invalid. */
    cJSON *plan_instr = NULL, *phase_instr = NULL, *task_instr = NULL;
    {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddStringToObject(p, "entity_type", "plan");
        cJSON_AddNumberToObject(p, "entity_id",   (double)plan_id);
        plan_instr = call_op(db, "instruction.list", p);
        cJSON_Delete(p);
    }
    if (phase_id > 0) {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddStringToObject(p, "entity_type", "phase");
        cJSON_AddNumberToObject(p, "entity_id",   (double)phase_id);
        phase_instr = call_op(db, "instruction.list", p);
        cJSON_Delete(p);
    }
    if (task_id > 0) {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddStringToObject(p, "entity_type", "task");
        cJSON_AddNumberToObject(p, "entity_id",   (double)task_id);
        task_instr = call_op(db, "instruction.list", p);
        cJSON_Delete(p);
    }

    /* 8. task.list pending limit 5 — the "Up next" queue for the plan. */
    cJSON *pending = NULL;
    {
        cJSON *p = cJSON_CreateObject();
        cJSON_AddNumberToObject(p, "plan_id", (double)plan_id);
        cJSON_AddBoolToObject  (p, "pending", 1);
        cJSON_AddNumberToObject(p, "limit",   5);
        pending = call_op(db, "task.list", p);
        cJSON_Delete(p);
    }

    next_render(project, plan_obj, phase_obj, task_obj,
                plan_instr, phase_instr, task_instr,
                pending);

    if (project)     cJSON_Delete(project);
    if (plan_obj)    cJSON_Delete(plan_obj);
    if (phase_obj)   cJSON_Delete(phase_obj);
    if (task_obj)    cJSON_Delete(task_obj);
    if (plan_instr)  cJSON_Delete(plan_instr);
    if (phase_instr) cJSON_Delete(phase_instr);
    if (task_instr)  cJSON_Delete(task_instr);
    if (pending)     cJSON_Delete(pending);
    ipman_db_close(db);
    return 0;
}

/* Wire validation rejects limit outside [1, 500]. We clamp client-side so
 * that `ipman -LG --limit 1000` produces 500 rows instead of an error,
 * matching the documented "clamps to 500" behavior. */
#define IPMAN_LOG_DEFAULT_LIMIT 20
#define IPMAN_LOG_MIN_LIMIT     1
#define IPMAN_LOG_MAX_LIMIT     500

/* Maximum visible width of the rendered details cell. Beyond this the cell
 * is truncated with "…" so a single noisy event cannot blow up table width. */
#define IPMAN_LOG_DETAILS_MAX 80

static int run_log(int argc, char **argv) {
    int  limit         = IPMAN_LOG_DEFAULT_LIMIT;
    int  summary_only  = 0;

    for (int i = 2; i < argc; ++i) {
        if (strcmp(argv[i], "--summary-only") == 0) {
            summary_only = 1;
        } else if (strcmp(argv[i], "--limit") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "ipman log: --limit requires a value\n");
                return 1;
            }
            char *end = NULL;
            long n = strtol(argv[++i], &end, 10);
            if (end == argv[i] || *end != '\0') {
                fprintf(stderr, "ipman log: --limit must be a positive integer\n");
                return 1;
            }
            if (n < IPMAN_LOG_MIN_LIMIT) n = IPMAN_LOG_MIN_LIMIT;
            if (n > IPMAN_LOG_MAX_LIMIT) n = IPMAN_LOG_MAX_LIMIT;
            limit = (int)n;
        } else {
            fprintf(stderr, "ipman log: unknown flag: %s\n", argv[i]);
            return 1;
        }
    }

    char home[PATH_MAX], dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    if (open_workspace(&db, home, sizeof home, dbpath, sizeof dbpath, 0, NULL) != 0)
        return 1;

    cJSON *params = cJSON_CreateObject();
    cJSON_AddNumberToObject(params, "limit", limit);
    cJSON *result = call_op(db, "event.list", params);
    cJSON_Delete(params);
    if (result == NULL) { ipman_db_close(db); return 1; }

    cli_table_t t;
    if (summary_only) {
        const char *headers[] = {"ID", "When", "Event", "Entity", "Summary"};
        cli_table_init(&t, 5, headers);
    } else {
        const char *headers[] = {"ID", "When", "Event", "Entity", "Summary", "Details"};
        cli_table_init(&t, 6, headers);
    }

    cJSON *events = cJSON_GetObjectItemCaseSensitive(result, "events");
    cJSON *ev;
    cJSON_ArrayForEach(ev, events) {
        cJSON *id          = cJSON_GetObjectItemCaseSensitive(ev, "id");
        cJSON *when        = cJSON_GetObjectItemCaseSensitive(ev, "event_at");
        cJSON *event_type  = cJSON_GetObjectItemCaseSensitive(ev, "event_type");
        cJSON *entity_type = cJSON_GetObjectItemCaseSensitive(ev, "entity_type");
        cJSON *entity_id   = cJSON_GetObjectItemCaseSensitive(ev, "entity_id");
        cJSON *summary     = cJSON_GetObjectItemCaseSensitive(ev, "summary");
        cJSON *details     = cJSON_GetObjectItemCaseSensitive(ev, "details");

        char id_str[16] = "";
        if (cJSON_IsNumber(id))
            snprintf(id_str, sizeof id_str, "%d", (int)id->valuedouble);

        char entity_str[64] = "";
        if (cJSON_IsString(entity_type) && cJSON_IsNumber(entity_id))
            snprintf(entity_str, sizeof entity_str, "%s/%d",
                     entity_type->valuestring, (int)entity_id->valuedouble);

        /* Trim the timestamp to date+time without sub-seconds */
        char when_str[32] = "";
        if (cJSON_IsString(when)) {
            snprintf(when_str, sizeof when_str, "%.19s", when->valuestring);
        }

        char details_str[IPMAN_LOG_DETAILS_MAX + 8] = "";
        char *details_owned = NULL;
        if (!summary_only && details != NULL && !cJSON_IsNull(details)) {
            details_owned = cJSON_PrintUnformatted(details);
            if (details_owned != NULL) {
                size_t n = strlen(details_owned);
                if (n <= IPMAN_LOG_DETAILS_MAX) {
                    snprintf(details_str, sizeof details_str, "%s", details_owned);
                } else {
                    /* Truncate and mark with a single-byte ellipsis (UTF-8 "…"
                     * is 3 bytes, but cli_output's width math counts bytes —
                     * we keep it ASCII to avoid a width mismatch). */
                    snprintf(details_str, sizeof details_str, "%.*s...",
                             IPMAN_LOG_DETAILS_MAX - 3, details_owned);
                }
                free(details_owned);
            }
        }

        if (summary_only) {
            const char *row[] = {
                id_str,
                when_str,
                (event_type && cJSON_IsString(event_type)) ? event_type->valuestring : "",
                entity_str,
                (summary    && cJSON_IsString(summary))    ? summary->valuestring    : "",
            };
            cli_table_add_row(&t, row);
        } else {
            const char *row[] = {
                id_str,
                when_str,
                (event_type && cJSON_IsString(event_type)) ? event_type->valuestring : "",
                entity_str,
                (summary    && cJSON_IsString(summary))    ? summary->valuestring    : "",
                details_str,
            };
            cli_table_add_row(&t, row);
        }
    }

    cli_table_print(&t, stdout);
    cli_table_free(&t);
    cJSON_Delete(result);
    ipman_db_close(db);
    return 0;
}

int main(int argc, char **argv) {
    ipman_log_init();

    /* Strip --dry-run from argv before dispatch so it is position-independent
     * and the per-verb arg parsers do not see it as an unknown flag. The
     * write verbs below check g_dry_run just before their dispatch call. */
    for (int i = 1; i < argc; ) {
        if (strcmp(argv[i], "--dry-run") == 0) {
            g_dry_run = 1;
            for (int j = i; j < argc - 1; ++j) argv[j] = argv[j + 1];
            argv[--argc] = NULL;
        } else {
            ++i;
        }
    }

    const char *cmd = (argc >= 2) ? parse_command(argv[1]) : NULL;

    if (cmd == NULL && argc >= 2) {
        fprintf(stderr, "unknown command: %s\nRun `ipman --usage` for help.\n", argv[1]);
        return 1;
    }
    if (cmd != NULL && strcmp(cmd, "usage")  == 0) { print_usage(stdout); return 0; }
    if (cmd != NULL && strcmp(cmd, "version") == 0) { fprintf(stdout, "ipman %s\n", IPMAN_VERSION); return 0; }
    if (cmd != NULL && strcmp(cmd, "init")   == 0) { return run_init(); }
    if (cmd != NULL && strcmp(cmd, "migrate-encrypt") == 0) { return run_migrate_encrypt(); }
    if (cmd != NULL && strcmp(cmd, "export")      == 0) { return run_export(argc, argv); }
    if (cmd != NULL && strcmp(cmd, "import-plan") == 0) { return run_import_plan(argc, argv); }
    if (cmd != NULL && strcmp(cmd, "sql")         == 0) { return run_sql_cmd(argc, argv); }
    if (cmd != NULL && strcmp(cmd, "status") == 0) { return run_status(); }
    if (cmd != NULL && strcmp(cmd, "ls")     == 0) { return run_ls(); }
    if (cmd != NULL && strcmp(cmd, "log")    == 0) { return run_log(argc, argv); }
    if (cmd != NULL && strcmp(cmd, "next")   == 0) { return run_next(); }
    if (cmd != NULL && strcmp(cmd, "render") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: ipman --render <plan>\n");
            return 1;
        }
        return run_render(argv[2]);
    }
    if (cmd != NULL && strcmp(cmd, "show") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: ipman --show <uid|label|id>\n");
            return 1;
        }
        return run_show(argv[2]);
    }
    if (cmd != NULL && strcmp(cmd, "start") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: ipman --start <task-uid|label|id>\n");
            return 1;
        }
        return run_start(argv[2]);
    }
    if (cmd != NULL && strcmp(cmd, "close") == 0) {
        return run_close(argc, argv);
    }
    if (cmd != NULL && strcmp(cmd, "cancel") == 0) {
        return run_cancel(argc, argv);
    }
    if (cmd != NULL && strcmp(cmd, "close-phase") == 0) {
        return run_close_phase(argc, argv);
    }
    if (cmd != NULL && strcmp(cmd, "cancel-phase") == 0) {
        return run_cancel_phase(argc, argv);
    }
    if (cmd != NULL && strcmp(cmd, "defer") == 0) {
        return run_defer(argc, argv);
    }
    if (cmd != NULL && strcmp(cmd, "current") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: ipman --current <task-or-phase-uid|label|id>\n");
            return 1;
        }
        return run_current(argv[2]);
    }
    if (cmd != NULL && strcmp(cmd, "activate") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: ipman --activate <plan-uid|label|id>\n");
            return 1;
        }
        return run_activate(argv[2]);
    }
    if (cmd != NULL && strcmp(cmd, "b64") == 0) {
        g_b64_mode = 1;
    }
    if (isatty(STDIN_FILENO)) {
        print_usage(stdout);
        return 0;
    }

    /* ---- open initialized workspace + migrations ------------------ */
    char home[PATH_MAX];
    char dbpath[PATH_MAX];
    sqlite3 *db = NULL;
    int schema_version = 0;
    int workspace_rc = open_workspace(&db, home, sizeof home,
                                      dbpath, sizeof dbpath,
                                      0, &schema_version);
    if (workspace_rc != 0) return workspace_rc;

    /* ---- read stdin ---------------------------------------------- */
    char   *body = NULL;
    size_t  body_len = 0;
    size_t  max_bytes = resolve_max_request_bytes();
    int     read_rc = ipman_read_all(stdin, max_bytes, &body, &body_len);
    if (read_rc == -2) {
        cJSON *details = cJSON_CreateObject();
        if (details != NULL) {
            cJSON_AddNumberToObject(details, "limit_bytes", (double)max_bytes);
            cJSON_AddNumberToObject(details, "received_bytes", (double)body_len);
        }
        char msg[160];
        snprintf(msg, sizeof msg,
                 "request body exceeds %zu-byte limit", max_bytes);
        cJSON *resp = ipman_response_err(NULL, IPMAN_ERR_INVALID_REQUEST,
                                        msg, details);
        emit_response(resp);
        if (resp) cJSON_Delete(resp);
        ipman_db_close(db);
        return 1;
    }
    if (read_rc != 0) {
        ipman_db_close(db);
        return emit_fatal(NULL, IPMAN_ERR_INTERNAL, "failed to read stdin");
    }
    if (g_b64_mode) {
        char *decoded = NULL;
        size_t decoded_len = 0;
        if (ipman_base64_decode(body, body_len, &decoded, &decoded_len) != 0) {
            free(body);
            ipman_db_close(db);
            return emit_fatal(NULL, IPMAN_ERR_INVALID_REQUEST,
                              "invalid base64 input");
        }
        free(body);
        body = decoded;
        body_len = decoded_len;
    }

    /* ---- parse --------------------------------------------------- */
    ipman_request_t     req;
    ipman_error_code_t  perr_code = IPMAN_ERR_INVALID_REQUEST;
    const char        *perr_msg  = NULL;
    char              *parsed_id = NULL;
    int rc = ipman_request_parse(body, &req, &perr_code, &perr_msg, &parsed_id);
    free(body);

    if (rc != 0) {
        ipman_log_warn("parse failed",
                      "code=%s request_id=%s msg=\"%s\"",
                      ipman_error_code_str(perr_code),
                      parsed_id ? parsed_id : "(null)",
                      perr_msg ? perr_msg : "");
        cJSON *resp = ipman_response_err(parsed_id, perr_code, perr_msg, NULL);
        emit_response(resp);
        if (resp) cJSON_Delete(resp);
        emit_parse_error_tip();
        free(parsed_id);
        ipman_db_close(db);
        return ipman_error_is_fatal(perr_code) ? 1 : 0;
    }
    free(parsed_id); /* we have req.request_id borrowed from req.root now */

    /* ---- dispatch ------------------------------------------------- */
    ipman_log_info("request",
                  "op=%s request_id=%s actor=%s",
                  req.op, req.request_id, req.actor);

    cJSON *resp = NULL;
    int disp_rc = ipman_dispatch(&req, db, &resp);
    emit_response(resp);
    if (resp) cJSON_Delete(resp);

    cJSON_Delete(req.root);
    ipman_db_close(db);

    (void)schema_version;
    return disp_rc == -2 ? 1 : 0;
}
